# Generated by Django 4.1.5 on 2023-03-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_review'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
