# Generated by Django 4.1.5 on 2023-03-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wocks_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField()),
            ],
            options={
                'db_table': 'size',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wocks_admin.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wocks_admin.size')),
            ],
            options={
                'db_table': 'variants',
            },
        ),
    ]
